# Docker-compose file for Datasette interface

services:

  datasette:
    image: datasette-with-plugins
    container_name: multicat
    restart: unless-stopped
    ports:
        - "8001:8001"
    volumes:
        - .:/mnt

    entrypoint: |
        datasette -p 8001 -h 0.0.0.0 -i /mnt/multicat.db
        --reload
        --metadata /mnt/metadata.yml
        --static assets:/mnt/static
        --template-dir /mnt/templates
